name: Install Just
description: Install Just to system path
runs:
  using: "composite"
  steps:
    - name: Install just
      uses: extractions/setup-just@v3

    - name: Install globally
      shell: bash
      run: |
        sudo cp "$(command -v just)" /usr/local/bin/just
