#!/usr/bin/env bash

# SCRIPT VERSION
VER=2
IMAGE_NAME=$(jq -r '."image-name"' /usr/share/pulsar/image-info.json)
FULL_VER="$VER-$IMAGE_NAME"

VER_FILE="/etc/pulsar/first-run-version"
VER_RAN=$(cat $VER_FILE)

# Run script if updated
if [[ -f $VER_FILE && $FULL_VER = $VER_RAN ]]; then
  echo "Flatpak manager v$FULL_VER has already ran. Exiting..."
  exit 0
fi


echo "Fixing libvirt labels..."
restorecon -rv /var/{lib,log}/libvirt

echo "Fixing cron labels..."
restorecon -rv /var/spool/cron


# create/update VER_FILE
mkdir -p /etc/pulsar
echo $FULL_VER > $VER_FILE