name: Build Pulsar
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 22 * * 5'  # 10pm UTC on Friday (5/6pm EDT) - after upstream builds and before auto-updates at 4am Saturday
  push:
    branches:
      - main
      - testing
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:
    inputs:
      # Run with this periodically to analyze the image again
      # As package drift will make the plan eventually non-ideal
      # (existing users will have to redownload most of the image)
      fresh-rechunk:
        description: 'Clear rechunk history'
        type: boolean
        default: false

env:
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image_name: [pulsar, pulsar-cli]
        major_version: [44]
        include:
          - image_name: pulsar-deck
            major_version: 43

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      # mount /mnt as /var/lib/containers
      - name: Mount BTRFS for podman storage
        id: container-storage-action
        uses: ublue-os/container-storage-action@dc1f4c8f17b672069e921f001132f7cf98a423a6
        continue-on-error: true
        with:
          target-dir: /var/lib/containers
          mount-opts: compress-force=zstd:2
          loopback-free: '1'

      - name: Install Just
        run: |
          /home/linuxbrew/.linuxbrew/bin/brew install just
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      # this first run of `just` helps makes sure /run/user/(uid)/just is created.
      # if the first run is a `sudo just`, permissions get dumb.
      - name: Check justfiles
        shell: bash
        run: |
          just check

      - name: Matrix Variables
        shell: bash
        run: |
          IMAGE_NAME="${{ matrix.image_name }}"
          MAJOR_VERSION="${{ matrix.major_version }}"
          FRESH_RECHUNK="${{ github.event.inputs.fresh-rechunk }}"
          DEFAULT_TAG="${{ github.ref_name == 'main' && 'stable' || 'testing' }}"
          ALIAS_TAGS="$(just get-tags ${DEFAULT_TAG} ${MAJOR_VERSION})"

          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "MAJOR_VERSION=${MAJOR_VERSION}" >> $GITHUB_ENV
          echo "FRESH_RECHUNK=${FRESH_RECHUNK}" >> $GITHUB_ENV
          echo "DEFAULT_TAG=${DEFAULT_TAG}" >> $GITHUB_ENV
          echo "ALIAS_TAGS=${ALIAS_TAGS}" >> $GITHUB_ENV
          

      - name: Build Image
        shell: bash
        run: |
          sudo -E $(command -v just) build ${{ env.IMAGE_NAME }} ${{ env.MAJOR_VERSION }} ${{ env.DEFAULT_TAG }}

      - name: Rechunk Image
        shell: bash
        run: |
          sudo -E $(command -v just) rechunk ${{ env.IMAGE_NAME }} ${{ env.MAJOR_VERSION }} ${{ env.DEFAULT_TAG }} ${{ env.FRESH_RECHUNK }}

      - name: Check Secureboot
        shell: bash
        run: |
          sudo -E $(command -v just) secureboot ${{ env.IMAGE_NAME }} ${{ env.DEFAULT_TAG }}

      - name: Tag Image
        shell: bash
        run: |
          sudo -E $(command -v just) tag-image ${{ env.IMAGE_NAME }} ${{ env.MAJOR_VERSION }} ${{ env.DEFAULT_TAG }}

      - name: Lowercase Registry
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
        run: |
          echo "LOWERCASE_REGISTRY=${IMAGE_REGISTRY,,}" >> $GITHUB_ENV

      - name: Push To GHCR
        uses: Wandalen/wretry.action@v3.5.0
        id: push
        if: github.event_name != 'pull_request'
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        with:
          action: redhat-actions/push-to-registry@v2
          attempt_limit: 3
          attempt_delay: 15000
          with: |
            image: ${{ env.IMAGE_NAME }}
            tags: ${{ env.ALIAS_TAGS }}
            registry: ${{ env.LOWERCASE_REGISTRY }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}

      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v4.1.0

      - name: Sign container image
        if: github.event_name != 'pull_request'
        env:
          TAGS: ${{ steps.push.outputs.digest }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          LOWERCASE: ${{ env.LOWERCASE_REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${LOWERCASE}/${IMAGE_NAME}@${TAGS}

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
